import { expect, test } from "vitest";

import { parseHelpIssue } from "../../scripts/help/parse-help-issue.mjs";

function issueBody(fields: Array<[string, string]>) {
  return fields
    .map(([heading, value]) => `### ${heading}\n\n${value}`)
    .join("\n\n");
}

const projectManifest = {
  schema_version: 1,
  request_kind: "project-report",
  origin: {
    page_url: "/help/report-project/",
    site_revision: "29962b44",
  },
  payload: {
    project_id: "sillytavern-sillytavern",
    canonical_source: "https://github.com/SillyTavern/SillyTavern",
    category: "unsafe-or-malicious",
    report: "The latest release downloads an unexpected executable.",
    requested_outcome: "Temporarily hide this listing.",
    evidence: "https://github.com/SillyTavern/SillyTavern/issues/1",
  },
} as const;

const missingManifestError = {
  valid: false,
  errors: [
    "This issue needs the complete Help manifest generated by Tavernary.",
  ],
};

test("uses a valid Help manifest when every readable field differs", () => {
  const body = issueBody([
    ["Project", "Wrong visible value — https://example.com/wrong"],
    ["Category", "Something else about this listing"],
    ["What should be reviewed?", "Wrong visible report"],
    ["Requested outcome", "Wrong visible outcome"],
    ["Supporting evidence", "https://example.com/wrong"],
    ["Help manifest", `\`\`\`json\n${JSON.stringify(projectManifest)}\n\`\`\``],
  ]);

  expect(parseHelpIssue(body)).toEqual({
    valid: true,
    source: "manifest",
    manifest: projectManifest,
  });
});

test.each([
  ["an absent manifest heading", issueBody([["Category", "Accessibility"]])],
  [
    "an empty manifest",
    issueBody([
      ["Category", "Accessibility"],
      ["Help manifest", "_No response_"],
    ]),
  ],
])("requires a Tavernary manifest for %s", (_name, body) => {
  expect(parseHelpIssue(body)).toEqual(missingManifestError);
});

test("rejects malformed JSON without trusting complete readable fields", () => {
  const body = issueBody([
    [
      "Project",
      "sillytavern-sillytavern — https://github.com/SillyTavern/SillyTavern",
    ],
    ["Category", "Incorrect or outdated card information"],
    ["What should be reviewed?", "The summary is outdated."],
    ["Requested outcome", "_No response_"],
    ["Supporting evidence", "_No response_"],
    ["Help manifest", "```json\n{not-json}\n```"],
  ]);

  expect(parseHelpIssue(body)).toEqual({
    valid: false,
    errors: ["Help manifest is not valid JSON."],
  });
});

test("rejects an unsupported manifest version", () => {
  const body = issueBody([
    [
      "Help manifest",
      `\`\`\`json\n${JSON.stringify({
        ...projectManifest,
        schema_version: 2,
      })}\n\`\`\``,
    ],
  ]);

  expect(parseHelpIssue(body)).toEqual({
    valid: false,
    errors: expect.arrayContaining(["Help request must use schema version 1."]),
  });
});

test("complete readable fields cannot construct a Help payload", () => {
  const body = issueBody([
    ["Category", "Accessibility"],
    ["Page URL", "https://tavernary.org/help/"],
    ["What happened?", "The focus indicator disappears."],
    ["What did you expect?", "The focused control remains visible."],
    ["Steps to reproduce", "Open Help and press Tab."],
    ["Browser", "Firefox 128"],
    ["Device", "Windows 11 desktop"],
    ["Additional context", "_No response_"],
    ["Help manifest", "_No response_"],
  ]);

  expect(parseHelpIssue(body)).toEqual(missingManifestError);
});

test("rejects duplicate manifest headings", () => {
  const body = [
    issueBody([["Help manifest", "_No response_"]]),
    "### Help manifest",
    "",
    JSON.stringify(projectManifest),
  ].join("\n\n");

  expect(parseHelpIssue(body)).toEqual({
    valid: false,
    errors: ["Help issue contains a duplicate recognized form heading."],
  });
});

test("allows repeated unrecognized headings inside readable content", () => {
  const body = [
    "### Notes",
    "",
    "First public note.",
    "",
    "### Notes",
    "",
    "Second public note.",
    "",
    "### Help manifest",
    "",
    `\`\`\`json\n${JSON.stringify(projectManifest)}\n\`\`\``,
  ].join("\n");

  expect(parseHelpIssue(body)).toEqual({
    valid: true,
    source: "manifest",
    manifest: projectManifest,
  });
});
