import { expect, test } from "vitest";

import { parseProjectSubmissionIssue } from "../../scripts/submissions/parse-project-submission.mjs";

const legacyV3Body = `
### Project manifest
\`\`\`json
{
  "schema_version": 3,
  "project_type": "extension",
  "primary_function": "generation-reasoning",
  "source_url": "https://github.com/Owner/Repo",
  "name": "Example",
  "description": null,
  "frontends": { "known_ids": ["sillytavern"], "other": [] },
  "frontend_independent": false,
  "additional_context": null
}
\`\`\`
`;

test("fails closed on a new schema-v3 manifest but recovers it when already admitted", () => {
  expect(parseProjectSubmissionIssue(legacyV3Body)).toEqual({
    valid: false,
    source: "manifest",
    errors: [
      "Submission manifest version 3 is retired. Regenerate the request with Tavernary's current project form.",
    ],
  });
  expect(
    parseProjectSubmissionIssue(legacyV3Body, { allowLegacyV3: true }),
  ).toMatchObject({
    valid: true,
    source: "manifest",
    manifest: {
      schema_version: 4,
      metadata: {
        summary: { mode: "automatic" },
        tags: { mode: "automatic" },
      },
    },
  });
});

test("uses a valid v4 manifest when every readable field contradicts it", () => {
  const result = parseProjectSubmissionIssue(`
### Project Type
Frontend
### Primary function
Frontend
### Project URL
https://github.com/Wrong/Heading
### Description choice
Write the description myself
### Short Description
Wrong readable summary.
### Tag choice
Set tags myself
### Tags
manage-context-limits
### Supported frontends
Wrong Frontend
### Frontend-independent
Yes
### Supported model families
gpt
### Completion formats
text-completion
### Project manifest
\`\`\`json
{
  "schema_version": 4,
  "project_type": "extension",
  "primary_function": "generation-reasoning",
  "source_url": "https://github.com/Owner/Repo",
  "frontends": { "known_ids": ["sillytavern"], "other": [] },
  "frontend_independent": false,
  "additional_context": "Manifest context.",
  "metadata": {
    "summary": { "mode": "automatic" },
    "tags": { "mode": "automatic" }
  }
}
\`\`\`
`);

  expect(result).toMatchObject({
    valid: true,
    source: "manifest",
    manifest: {
      project_type: "extension",
      primary_function: "generation-reasoning",
      source_url: "https://github.com/Owner/Repo",
      frontends: { known_ids: ["sillytavern"], other: [] },
      frontend_independent: false,
      additional_context: "Manifest context.",
      metadata: {
        summary: { mode: "automatic" },
        tags: { mode: "automatic" },
      },
    },
  });
});

test.each([
  {
    name: "has no manifest field",
    body: `
### Project Type
Extension
### Project URL
https://github.com/Owner/Repo
### Frontend-independent
No
`,
  },
  {
    name: "has an empty manifest response",
    body: `
### Project Type
System Preset
### Project URL
https://github.com/Owner/Preset
### Supported model families
claude
### Completion formats
chat-completion
### Project manifest
_No response_
`,
  },
  {
    name: "has GitHub's empty rendered JSON fence",
    body: `
### Project Type
Frontend
### Project URL
https://github.com/Owner/Frontend
### Project manifest
\`\`\`json

\`\`\`
`,
  },
])("rejects readable project fields when the issue $name", ({ body }) => {
  expect(parseProjectSubmissionIssue(body)).toEqual({
    valid: false,
    source: "manifest",
    errors: [
      "This issue needs the complete Project manifest generated by Tavernary.",
    ],
  });
});

test("rejects malformed embedded JSON without consulting readable fields", () => {
  expect(
    parseProjectSubmissionIssue(`
### Project Type
Frontend
### Project URL
https://github.com/Owner/Valid
### Project manifest
{not-json}
`),
  ).toEqual({
    valid: false,
    source: "manifest",
    errors: ["Project manifest must be valid JSON."],
  });
});
