import { readFile } from "node:fs/promises";

import { expect, test } from "vitest";

test("documents project submission automation and recovery controls", async () => {
  const [
    readme,
    contributorGuide,
    runbook,
    lifecycle,
    issueForm,
    schemaReference,
    enrichmentReference,
  ] = await Promise.all([
    readFile("README.md", "utf8"),
    readFile("docs/contributing/submission-and-review.md", "utf8"),
    readFile("docs/maintenance/operations-runbook.md", "utf8"),
    readFile("docs/architecture/catalog-lifecycle.md", "utf8"),
    readFile(".github/ISSUE_TEMPLATE/01-project-submission.yml", "utf8"),
    readFile("docs/reference/project-record-schema.md", "utf8"),
    readFile("docs/reference/catalog-enrichment-report.md", "utf8"),
  ]);

  for (const phrase of [
    "generate-project-submission.yml",
    "submission-pr-open",
    "submission-declined",
    "force_regeneration",
    "automation/project-submission-<issue-number>",
  ]) {
    expect(runbook).toContain(phrase);
  }

  expect(runbook).toContain(
    "Allow GitHub Actions to create and\napprove pull requests",
  );
  expect(runbook).toContain("PROJECT_AUTO_PUBLICATION_ENABLED");
  expect(runbook).toContain("publish-project-transaction.yml");
  expect(runbook).toContain("exact validated head SHA");
  expect(runbook).toContain("post-publication");
  expect(runbook).not.toContain(
    "Automation creates but never approves its own PR",
  );
  expect(contributorGuide).toContain(
    "A request appears in the catalog only after all required checks pass.",
  );
  expect(contributorGuide).toContain("consensual adult content");
  expect(contributorGuide).toContain("ordinary profanity");
  expect(contributorGuide).toMatch(/advisory and\s+post-publication/u);
  expect(contributorGuide).toContain(
    "Verified-owner delisting is permanent for that source.",
  );
  expect(contributorGuide).toContain(
    "builder's frontend choices come from the current catalog",
  );
  expect(contributorGuide).toMatch(
    /Manual summary and tag choices are used only after GitHub verifies repository\s+ownership\./u,
  );
  expect(lifecycle).toContain(
    "Closing the generated PR without\n   merge declines the submission",
  );
  expect(lifecycle).toContain("External System Presets");
  expect(readme).toContain("static submission builder");
  expect(readme).toContain("No account, database service, or\nruntime API");
  for (const document of [readme, contributorGuide]) {
    expect(document).toContain(
      "Frontends and Extensions require a public GitHub or Codeberg repository.",
    );
  }
  expect(issueForm).toContain("Begin in Tavernary");
  expect(issueForm).toContain(
    "Required automation payload generated by Tavernary",
  );
  expect(runbook).toContain("providers.codeberg");
  expect(lifecycle).toContain("data/snapshots/codeberg/*.json");
  expect(contributorGuide).toMatch(
    /primary\s+function selected in the form remains the submitted category/u,
  );
  expect(issueForm).toMatch(/Maximum 220\s+characters\./u);
  expect(issueForm).toMatch(
    /GitHub verifies the submitter as the personal\s+repository owner/u,
  );
  expect(lifecycle).toContain(
    "Frontends always use `frontend`; System Presets always use `preset`",
  );
  expect(lifecycle).toMatch(
    /never changes the canonical\s+`primary_function`/u,
  );
  expect(enrichmentReference).toContain("summary, tags, and `metadata_status`");
  expect(enrichmentReference).toContain("intake-only classification review");
  expect(schemaReference).not.toContain("`uncategorized`");
});
