export const admittedGithubExtension = {
  status: "admitted" as const,
  manifest: {
    schema_version: 4 as const,
    project_type: "extension" as const,
    primary_function: "generation-reasoning",
    source_url: "https://github.com/Owner/Repo",
    frontends: { known_ids: ["sillytavern"], other: [] },
    frontend_independent: false,
    additional_context: null,
    metadata: {
      summary: { mode: "automatic" as const },
      tags: { mode: "automatic" as const },
    },
  },
  identity: {
    kind: "repository" as const,
    provider: "github" as const,
    canonicalUrl: "https://github.com/Owner/Repo",
    repository: "Owner/Repo",
    repositoryId: 42,
    owner: "Owner",
    name: "Repo",
  },
  frontendIds: ["sillytavern"],
  warnings: [],
};

export const observation = {
  provider: "github" as const,
  sourceId: "github-42",
  repository: {
    id: 42,
    owner: "Owner",
    name: "Repo",
    url: "https://github.com/Owner/Repo",
    description: "Repository description.",
    defaultBranch: "main",
    headSha: "a".repeat(40),
    headCommittedAt: "2026-07-25T17:00:00.000Z",
    archived: false,
    fork: false,
    parent: null,
    createdAt: "2026-01-01T00:00:00.000Z",
    sizeKb: 12,
  },
  community: {
    starsCount: 3,
    forksCount: 2,
    watchersCount: 1,
  },
  latestReleaseAt: null,
  coarseLicenseSpdxId: "MIT",
};

export const snapshot = {
  schema_version: 4 as const,
  provider: "github" as const,
  source_id: "github-42",
  repository: {
    id: 42,
    owner: "Owner",
    name: "Repo",
    url: "https://github.com/Owner/Repo",
    description: "Repository description.",
    default_branch: "main",
    head_sha: "a".repeat(40),
    head_committed_at: "2026-07-25T17:00:00.000Z",
    archived: false,
    created_at: "2026-01-01T00:00:00.000Z",
    size_kb: 12,
  },
  source_health: "healthy" as const,
  activity: {
    latest_source_activity_at: null,
    source_weeks: [],
    provisional_weeks: Array.from({ length: 12 }, () => false),
    latest_release_at: null,
    evidence_status: "provisional" as const,
    baseline_completed_at: null,
    baseline_attempts: 0,
  },
  community: {
    stars_count: 3,
    forks_count: 2,
    watchers_count: 1,
    aggregate: 6,
  },
  license: {
    status: "osi-approved" as const,
    spdx_id: "MIT",
    source_path: "LICENSE",
  },
  refreshed_at: "2026-07-25T18:00:00.000Z",
  stale_since: null,
};
